export const combos = [
    ["WORM", "TEAR", "LAKE"],
    ["DUNK", "CAUSE", "BUMP"],
    ["MEM", "BOID", "POKE"],
    ["RING", "SMOKE", "DREAD"],
    ["LIE", "FROM", "FLOOD"],
    ["TOP", "HAT", "WORM"],
    ["ORPH", "JOY", "PUP"],
    ["RONG", "PING", "CANE"],
    ["MEM", "HAT", "DOG"],
    ["LUNG", "HOLE", "GLOBE"],
    ["RING", "RONG", "GUSH"],
    ["SICK", "PACK", "KISS"],
    ["TWIN", "BURN", "WING"],
    ["OLD", "DREAM", "FEEL"],
    ["BOID", "LUV", "LIE"],
    ["TOO", "JOKE", "FAR"],
    ["COW", "NOID", "STAG"],
    ["AS", "FLAT", "RATE"],
    ["ILL", "FEAR", "REAL"],
    ["SONG", "CELL", "CON"],
    ["FIRE", "FLAT", "SCAPE"],
    ["RAT", "SINK", "WORM"],
    ["TEAR", "TEAR", "LO"],
    ["GOOD", "FLAT", "TEAR"],
    ["FOUL", "WORM", "MOUTH"],
    ["DUMP", "TWIN", "FACE"],
    ["NO", "HEX", "TEAR"],
    ["MURK", "SPURT", "SNIB"],
    ["REAL", "EX", "SCAPE"],
    ["PIS", "POKE", "LIT"],
    ["CHURN", "DULL", "SUN"],
    ["GO", "GAZ", "CAM"],
    ["TIK", "TOAD", "KISS"],
    ["CRY", "COAL", "CELL"],
    ["NOID", "HELL", "GLOW"],
    ["PANG", "BOOM", "WRECK"],
    ["CUT", "LIFE", "WORLD"],
    ["DOG", "PIS", "PLOW"],
    ["NAIL", "GLOB", "CODE"],
    ["NOID", "DUMB", "BUMP"],
    ["FOOL", "HALF", "CRY"],
    ["CASH", "LESS", "BOIL"],
    ["AS", "LIFE", "MOUTH"],
    ["PEAK", "POKE", "DREAD"],
    ["TEMP", "RAT", "HAT"],
    ["WEPT", "WRONG", "RING"],
    ["SONG", "SINK", "BIRD"],
    ["DOG", "LESS", "SCAM"],
    ["SICK", "LIKE", "DREAM"],
    ["GATE", "TO", "SKY"],
    ["CHIN", "WOOD", "SLIP"],
    ["FOUL", "HAT", "FLAB"],
    ["RAT", "HISS", "SLUG"],
    ["BOOM", "GAZ", "MOUTH"],
    ["NOID", "BOID", "SCALP"],
    ["NO", "MESS", "LIFE"],
    ["FORM", "FROM", "BONE"],
    ["BLOOD", "DRY", "CRY"],
    ["SHIT", "GLOB", "CROW"],
    ["DREAM", "SLASH", "FAR"],
    ["BUY", "LIP", "LUMP"],
    ["RONG", "SHIT", "VEIN"],
    ["GRAB", "STUNG", "FLAB"],
    ["FOOL", "BOID", "MEM"],
    ["DUMP", "PIG", "WING"],
    ["FAIL", "CHING", "BAG"],
    ["RAGE", "FILL", "FEAR"],
    ["SMILE", "BURN", "LIE"],
    ["SMALL", "JOKE", "END"],
    ["STARE", "NEW", "URTH"],
    ["DED", "END", "DREAD"],
    ["SNOUT", "PUP", "SCAR"],
    ["LAF", "GAZE", "BONE"],
    ["PEEK", "PUP", "JOKE"],
    ["TEAR", "STARE", "FAIL"],
    ["NIP", "RIP", "MESS"],
    ["PEAK", "FEEL", "VOID"],
    ["KIT", "WAIL", "WAIL"],
    ["SOFT", "FROM", "SHOK"],
    ["TIK", "LIE", "POUND"],
    ["HEX", "CON", "GULL"],
    ["CHIN", "LESS", "LUMP"],
    ["MEE", "TO", "RUP"],
    ["THICK", "DREAD", "CROW"],
    ["COW", "CLAW", "SKIN"],
    ["FIRE", "RAT", "CHANT"],
    ["BOID", "SICK", "SNOUT"],
    ["CRASH", "ICE", "PIG"],
    ["REAL", "SMALL", "BAG"],
    ["CHIN", "SCAR", "SHAKE"],
    ["TWIN", "A", "FOOL"],
    ["PEEK", "TIC", "ARC"],
    ["MUG", "DRY", "LIE"],
    ["RAT", "PAIN", "FACE"],
    ["PAIN", "TAIL", "LUMP"],
    ["FOUL", "FAIL", "TEAR"],
    ["JOKE", "SHOK", "BOID"],
    ["DOG", "WEPT", "LIE"],
    ["LATE", "SNOW", "STORM"],
    ["GLOW", "SCAB", "RAT"],
    ["FANG", "FING", "RED"],
    ["SOFT", "VOID", "BOID"],
    ["APE", "FILL", "SNOUT"],
    ["THICK", "TURN", "POKE"],
    ["CUTE", "FEEL", "FALL"],
    ["KICK", "LIFE", "FUN"],
    ["TICK", "TOK", "..."],
    ["GAZ", "RUN", "CUST"],
    ["BIRD", "HALF", "TEAR"],
    ["BEE", "GAZE", "FAR"],
    ["RANT", "CUT", "SMILE"],
    ["CAP", "PUMP", "SCAM"],
    ["SARC", "BOOM", "BALL"],
    ["SNOUT", "SPURT", "RUP"],
    ["RAIN", "TEAR", "SAIL"],
    ["DREAM", "PRE", "PACK"],
    ["SMOKE", "TOAD", "SKIN"],
    ["DED", "RUN", "CRY"],
    ["AS", "MORE", "THING"],
    ["GUSH", "PIG", "DUNG"],
    ["DED", "WORLD", "CRY"],
    ["GOOD", "FUN", "CHILL"],
    ["FEAR", "NEG", "NIP"],
    ["TAIL", "TICK", "BOIL"],
    ["SLAK", "SHIT", "FACE"],
    ["TICK", "FULL", "FILL"],
    ["POD", "LIKE", "CUST"],
    ["SMALL", "LIP", "HOLE"],
    ["VEIN", "RIP", "HORN"],
    ["PACK", "TEAR", "SKY"],
    ["GLOB", "JOKE", "URTH"],
    ["DOVE", "SMILE", "ASH"],
    ["MUG", "FED", "JOKE"],
    ["RAT", "JOKE", "LIP"],
    ["JOY", "FILL", "SKY"],
    ["STORM", "SKIP", "EX"],
    ["DIP", "REAL", "SCAM"],
    ["LAF", "FOOL", "FAR"],
    ["ANG", "PING", "RAT"],
    ["ANG", "GLO", "SHOK"],
    ["DIP", "IT", "REAL"],
    ["CHUG", "DULL", "SHAKE"],
    ["SNOUT", "CRASH", "END"],
    ["GATE", "SPURT", "RAT"],
    ["RIP", "JAW", "CARB"],
    ["FOUL", "FLAT", "LATE"],
    ["TAIL", "SAIL", "CHIP"],
    ["CRIB", "PIG", "TAR"],
    ["VEIN", "JOKE", "HA"],
    ["PUP", "CROOK", "LIP"],
    ["JOY", "CRY", "LIFE"],
    ["RAIN", "RE", "BOT"],
    ["WRECK", "N", "RIG"],
    ["SARC", "NOR", "SPURT"],
    ["PIG", "TERR", "CHUK"],
    ["FOOL", "NAH", "LIFE"],
    ["GUSH", "POD", "LIFE"],
    ["DOG", "NOR", "CAB"],
    ["TURN", "FIR", "LIT"],
    ["ROSE", "RAIN", "JOKE"],
    ["RAT", "HOOK", "GIG"],
    ["LEFT", "LIKE", "PUP"],
    ["NEG", "DRY", "HEX"],
    ["PAIN", "TURN", "DROLL"],
    ["RONG", "SCAR", "KISS"],
    ["TOP", "FEAR", "FUN"],
    ["NAIL", "SCAM", "U"],
    ["U", "SCAM", "U"],
    ["U", "SCAM", "MEE"],
    ["JOY", "SCREM", "CROW"],
    ["TOO", "MORE", "SMILE"],
    ["NEG", "CHUG", "TIC"],
    ["TIC", "TICK", "GLOBE"],
    ["NIP", "SKIP", "CAT"],
    ["PUS", "POUT", "LOBE"],
    ["WORLD", "KON", "LIFE"],
    ["HAR", "MEANS", "HA"],
    ["BEAK", "LUNG", "PORT"],
    ["MESS", "SONG", "END"],
    ["GULL", "IS", "PIG"],
    ["AS", "POKE", "JOKE"],
    ["CUT", "LUV", "CROWN"],
    ["ANGLE", "FOOL", "FOOL"],
    ["LAF", "LUNG", "LAUGH"],
    ["WIDE", "EEL", "MOUTH"],
    ["GAZ", "MAUL", "THING"],
    ["DOG", "WAS", "CAT"],
    ["PUP", "SLIP", "PUS"],
    ["JEST", "CAM", "SNOUT"],
    ["FAT", "HEX", "LITE"],
    ["FOUL", "CRAWL", "SCAPE"],
    ["VOID", "SICK", "DOG"],
    ["WOOD", "SLASH", "GOIT"],
    ["PING", "FROM", "TAIL"],
    ["CLAW", "TICK", "POKE"],
    ["SHEAR", "NO", "DROLL"],
    ["LUMP", "SUM", "FANG"],
    ["FEAR", "LUV", "TEAR"],
    ["SNIB", "POKE", "KISS"],
    ["WORLD", "HONK", "BAG"],
    ["PIS", "POKE", "DREAM"],
    ["CRY", "JOKE", "POKE"],
    ["FLAB", "BONE", "SNOUT"],
    ["THICK", "TIC", "BONE"],
    ["CAT", "ANT", "COAL"],
    ["TOFF", "TOK", "DUNG"],
    ["PAIN", "NO", "DOG"],
    ["SCAR", "GAZ", "SCAB"],
    ["FEAR", "AND", "LAF"],
    ["SOFT", "CLAW", "BUMP"],
    ["MEE", "SAVE", "GLOB"],
    ["LESS", "KICK", "KICK"],
    ["FLAT", "PEEK", "BUMP"],
    ["SNIB", "TIK", "LIFE"],
    ["GLOW", "JOY", "CHIN"],
    ["FLAT", "TEAR", "CROW"],
    ["AS", "SNOW", "ICE"],
    ["FACE", "DIP", "LIKE"],
    ["SMALL", "FISH", "FUN"],
    ["GO", "FAR", "BONE"],
    ["A", "SKY", "PACK"],
    ["TEAR", "SKIP", "CHANT"],
    ["NO", "TO", "FEAR"],
    ["LIKE", "REAL", "WORM"],
    ["CRY", "PRE", "WILD"],
    ["LAUGH", "WAS", "SCAPE"],
    ["WORM", "HOOK", "TRICK"],
    ["WORM", "TOP", "SCALP"],
    ["FLAT", "PUMP", "SNOUT"],
    ["CRY", "POUT", "LIFE"],
    ["TEAR", "SUMP", "EYE"],
    ["SMILE", "GAZE", "PUS"],
    ["LAF", "SECT", "EYE"],
    ["LIFE", "WORM", "MEM"],
    ["TOK", "TEAR", "TING"],
    ["DUN", "SMILE", "TRICK"],
    ["FLAT", "PUMP", "JAW"],
    ["CAT", "RIP", "HOWL"],
    ["RIP", "NIP", "SMILE"],
    ['SICK', 'IS', 'CHECK'],
    ['LAUGH', 'TURN', 'HA'],
    ['TOO', 'TOK', 'HOOK'],
    ['BOID', 'HOOK', 'TRICK'],
    ['PAIN', 'FOUL', 'KISS'],
    ['BOOM', 'LESS', 'BEE'],
    ['TOAD', 'TEAR', 'MEM'],
    ['FAKE', 'MOUTH', 'SCAN'],
    ['ANGLE', 'RING', 'CAP'],
    ['FISH', 'RIG', 'FLOOD'],
    ['ORPH', 'PIS', 'RAIN'],
    ['TORN', 'NOID', 'HOWL'],
    ['PIG', 'GUSH', 'GAOT'],
    ['JEST', 'OR', 'SCAN'],
    ['SOFT', 'STARE', 'BOT'],
    ['WEPT', 'WEPT', 'WIN'],
    ['DED', 'CHEK', 'CAM'],
    ['AS', 'CHILL', 'DOG'],
    ['BOOM', 'DROLL', 'GULL'],
    ['TAR', 'LESS', 'TEAR'],
    ['TEAR', 'LESS', 'LIFE'],
    ['CHIN', 'SLIP', 'GAG'],
    ['WORLD', 'HAUNT', 'HOOK'],
    ['HA', 'SICK', 'REAL'],
    ['CLAW', 'BOT', 'KNOB'],
    ['BUY', 'BULK', 'ANGLE'],
    ['HALF', 'MY', 'MESS'],
    ['RING', 'A', 'WOOM'],
    ['SCAN', 'BURN', 'CHUK'],
    ['RAT', 'FEAR', 'FEEL'],
    ['CRY', 'STUNG', 'LIKE'],
    ['BOOT', 'FOUL', 'RAGE'],
    ['A', 'TOAD', 'EYE'],
    ['CUTE', 'NAIL', 'RED'],
    ['GUSH', 'BURN', 'TAR'],
    ['HALF', 'STUNG', 'TIP'],
    ['LAF', 'HISS', 'DAZE'],
    ['PEAK', 'BOOM', 'GAOT'],
    ['FLAT', 'SNOUT', 'FACE'],
    ['FOOL', 'TEAR', 'TRICK'],
    ['SING', 'SUM', 'SUN'],
    ['SUN', 'IS', 'SCAM'],
    ['HA', 'DULL', 'PONE'],
    ['SCAN', 'RAT', 'DOG'],
    ['KICK', 'BOT', 'DOG'],
    ['BOOM', 'IS', 'LAUGH'],
    ['TEAR', 'AS', 'WANT'],
    ['HA', 'TRICK', 'REAL'],
    ['DUMP', 'LESS', 'CARB'],
    ['NAIL', 'BE', 'CHIN'],
    ['LIQ', 'HORN', 'SCAR'],
    ['SMILE', 'TAIL', 'DUNG'],
    ['SICK', 'SCAM', 'STICK'],
    ['LUMP', 'FIT', 'RIG'],
    ['TIK', 'TOAD', 'TEETH'],
    ['WORM', 'LESS', 'GLOBE'],
    ['FOUL', 'NEVER', 'SONG'],
    ['LIKE', 'RAT', 'MOUTH'],
    ['BUMP', 'ANGLE', 'BEE'],
    ['WRECK', 'RATE', 'DIP'],
    ['BOT', 'KICK', 'TEAR'],
    ['JOKE', 'LESS', 'CRY'],
    ['SUMP', 'LO', 'BUMP'],
    ['CASH', 'RAIN', 'GAG'],
    ['ASH', 'BOT', 'RAIN'],
    ['ROCK', 'SCAR', 'LIFE'],
    ['SONG', 'FEEL', 'U'],
    ['CELL', 'WOOD', 'SCAM'],
    ['TRICK', 'HAT', 'WILD'],
    ['JEST', 'ZANG', 'DUNG'],
    ['AS', 'SKIN', 'CAT'],
    ['DROLL', 'SMOKE', 'RIG'],
    ['TRICK', 'TOK', 'PUSH'],
    ['TEAR', 'BOT', 'DUN'],
    ['ILL', 'IS', 'SKY'],
    ['REAL', 'RIG', 'ORPH'],
    ['ANGLE', 'LEAK', 'BAG'],
    ['LIQ', 'PUMP', 'WORLD'],
    ['WEPT', 'JOY', 'LIQ'],
    ['SICK', 'WORLD', 'HA'],
    ['NO', 'CRASH', 'TREE'],
    ['PAIN', 'LESS', 'DIP'],
    ['MEM', 'OR', 'GRIN'],
    ['PIG', 'CAUSE', 'GRIN'],
    ['JOKE', 'IS', 'WORM'],
    ['TEAR', 'LESS', 'DREAM'],
    ['TEAR', 'BOT', 'LESS']
];

export const imageIndices = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41
];

export const onomatos = [
    "BANG",
    "DANG",
    "BOOM",
    "CLANG",
    "CLONK",
    "DONK",
    "BONK",
    "DRIP",
    "DROP",
    "TIK",
    "TOK",
    "PING",
    "DING",
    "PANG",
    "ZWANG",
    "CUT",
    "SLASH",
    "ZONK",
    "KLOP",
    "KLONK",
    "ZOK",
    "ZOOM",
    "RING",
    "SNAP",
    "SLAP",
    "POP",
    "ZONG",
    "PONG",
    "ZANG",
    "CRASH",
    "CRAC",
    "PLING",
    "ZAP",
    "ZIP",
    "SNAP",
    "BLAM",
    "KLAC",
    "BEEP",
    "BLOP",
    "PLOP",
    "ZZZ",
    "HI",
    "HA"
];